all: true
check-coverage: true
include:
  - "src/**/*.js"
exclude:
  - "**/*.test.js"
  - "**/*router.js"
  - "src/assets/javascripts/*.js"
  - "src/assets/javascript/*.js"
  - "src/app/passport/*.js"
  - "src/lib/config.js"
  - "src/app.js"
report-dir: coverage
statements: 70
branches: 80
functions: 70
lines: 70
watermarks:
  statements:
    - 60
    - 90
  branches:
    - 80
    - 90
  functions:
    - 60
    - 90
  lines:
    - 60
    - 90
