name: Pre-merge checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Run unit tests
        run: yarn test
